### PR TITLE
MF-247: Setting FHIR Immunization resource URLs + Removing "resource" wrapper.

### PR DESCRIPTION
**Pull request by mks-d**
https://issues.openmrs.org/browse/MF-247

### What I have done:
1. I have set the correct FHIR URLs in **src/widgets/immunizations/immunizations.resource.tsx** (see [here](https://github.com/openmrs/openmrs-esm-patient-chart-widgets/pull/123/files#diff-f54da46daba0e34232d32493d3aef654R61) and [here](https://github.com/openmrs/openmrs-esm-patient-chart-widgets/pull/123/files#diff-f54da46daba0e34232d32493d3aef654R74)).
1. I have removed all reference to the wrapping `"resource"` key in the FHIR Immunization resources (+ adapted tests, mocks... etc.)

### CODE REVIEW

**Comment by brandones** [comment]
@mks-d What's this waiting on?

**Comment by FlorianRappl** [comment]
Any update on this one @mks-d ?

**Comment by mks-d** [comment]
@FlorianRappl, I think we could merge it for now. However:
- Editing immunizations is not supported, that's "ok" and it's a small fix.
- The backend PR is not merged yet.

So it's still a half baked feature at this point but merging this would make it move forward.

**Comment by FlorianRappl** [comment]
Understood - I've elevated the PR to review state.

From my perspective we can merge it - @brandones ?

cc @mks-d

**Review by FlorianRappl — APPROVED** [review]
LGTM :beers:!

**Pull request merged**
