### PR TITLE
MF-514 Identifiers should be comma-separated

### PR DESCRIPTION
**Pull request by harshit151001**
Files changed: `openmrs-esm-patient-chart-widgets/src/widgets/banner/patient-banner.component.tsx/`

changes :-
` {getPatientIdentifiers()}` --> ` {getPatientIdentifiers().join(", ")}`

### CODE REVIEW

**Comment by FlorianRappl** [comment]
Don't delete the file. Not sure what you want to achieve. Just take the incoming changes. That's all.

**Comment by harshit151001** [comment]
> Don't delete the file. Not sure what you want to achieve. Just take the incoming changes. That's all.

Sorry, I thought it will resolve conflicts, I have generated it again in latest commit.

**Comment by HerbertYiga** [comment]
@harshit151001  i still see you have some conflicts here

**Comment by harshit151001** [comment]
> @harshit151001 i still see you have some conflicts here

resolve conflicts is disabled for me @HerbertYiga

**Comment by HerbertYiga** [comment]
@harshit151001  do you wana  look at this https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/resolving-a-merge-conflict-using-the-command-line

**Comment by FlorianRappl** [comment]
Yes just use the command line.

```sh
git pull openmrs master
```

where `openmrs` is the name of the remote pointing to `https://github.com/openmrs/openmrs-esm-patient-chart-widget.git` (or ssh if you use that).

Now you should see some conflicts. Follow the instructions from @HerbertYiga's link to resolve them.

Otherwise, use your preferred IDE (e.g., VS Code has a nice Git integration where you can just right click and select "take all incoming").

**Comment by FlorianRappl** [comment]
I'll just close this.

This change is already part of the new monorepo.

**Comment by harshit151001** [comment]
Okay, I didn't knew about it.

**Pull request closed without merging**
