### PR TITLE
[MF-322] Adding 'Edit Patient' button to the patient banner

### PR DESCRIPTION
**Pull request by samuelmale**
**Ticket**: https://issues.openmrs.org/browse/MF-322

**Demo**:

### CODE REVIEW

**Comment by jonathandick** [comment]
@samuelmale could you post a gif of this?

**Comment by samuelmale** [comment]
> @samuelmale could you post a gif of this?

Added one..

**Review by FlorianRappl — APPROVED** [review]
LGTM! :beers:

**Comment by samuelmale** [comment]
@FlorianRappl Here is the parent PR: https://github.com/openmrs/openmrs-esm-patient-registration/pull/46

**Pull request merged**
