### PR TITLE
disabling future dates on the onSetDate field on the conditions form

### PR DESCRIPTION
**Pull request by mherman22**
- This is to solve the issue [mf-345](https://issues.openmrs.org/browse/MF-345). Previously the conditions form allowed the user to set a date in the future as the onset date for a particular condition. 
- What i did was to add validation to the date input that allows one to only enter today's date or older.
- 

conditions

### CODE REVIEW

**Review by brandones — APPROVED** [review]
LGTM, please resolve conflicts

**Comment by brandones** [comment]
Oh, but this repo is going away. This will be lost. Please open your PR against the `feature/monorepo` branch of patient-chart.

**Comment by mherman22** [comment]
Thanks @brandones lemi change this PR to the feature/monorepo as advised

**Comment by mherman22** [comment]
@brandones been at it for long. could you point me to where/how i can a this pr in the branch(feature/monorepo) of another repo

**Comment by mherman22** [comment]
am closing this PR. refer to https://github.com/openmrs/openmrs-esm-patient-chart/pull/219 for this very PR in the new monorepo of `patient-chart`

**Pull request closed without merging**
