### PR TITLE
MF-229: Error on saving allergy

### PR DESCRIPTION
**Pull request by Gayatri-Kodag**
MF-229 Error on saving allergy
Added a check for extension field in resource field in entry field of allergy list returned

### CODE REVIEW

**Comment by denniskigen** [comment]
Hi @Gayatri-Kodag, good work. Please move `mockPatientAllergyResultWithoutOnsetDate` to `__mocks__/allergy.mock.ts`.

**Comment by Gayatri-Kodag** [comment]
Hi @denniskigen , Thank you. I have moved `mockPatientAllergyResultWithoutOnsetDate` to `__mocks__/allergy.mock.ts`.

**Comment by jonathandick** [comment]
@denniskigen have you reviewed this? Is this ready to be merged?

**Comment by denniskigen** [comment]
Hi @Gayatri-Kodag, could you consider using [optional chaining](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Optional_chaining) to safely access the `valueDatetime` property in the `extension` array?

**Comment by FlorianRappl** [comment]
I think the proposal from @denniskigen is sound - would be better using `?.` and `??`.

**Comment by Gayatri-Kodag** [comment]
Thanks @denniskigen .I would make the changes to use optional chaining.

**Comment by denniskigen** [comment]
Hey @FlorianRappl, looks like the date bug we sorted out some time ago by wrapping the age calculator function in `Date.UTC` has appeared again, hence the failing CI build. I got it the same test failure locally as well. 

Screenshot 2020-05-29 at 21 52 11

**Comment by Gayatri-Kodag** [comment]
Hey @denniskigen, I am also getting the test failure locally. I have raised a new PR with all the above changes. Link to PR - https://github.com/openmrs/openmrs-esm-patient-chart-widgets/pull/91

**Comment by Gayatri-Kodag** [comment]
I am closing this PR raised a new PR including all the above changes.

**Pull request closed without merging**
