### PR TITLE
MF-219: Add height and weight widget translations

### PR DESCRIPTION
**Pull request by denniskigen**
https://issues.openmrs.org/browse/MF-219

This PR:

- Adds translations strings for the components that make up the height and weight widget.
- Bumps test statement coverage up to 93%.

Progress on i18n can be followed here: https://issues.openmrs.org/browse/MF-219

### CODE REVIEW

**Review by FlorianRappl — APPROVED** [review]
LGTM - great job :beers:!

**Comment by denniskigen** [comment]
NOTE: This PR is dependent on #107 because both the height and weight widget and the vitals widget reuse the vitals form.

**Comment by FlorianRappl** [comment]
Thanks for the remark @denniskigen  - PR #107 is now merged in. I think you can elevate the PR now.

**Comment by denniskigen** [comment]
> Thanks for the remark @denniskigen - PR #107 is now merged in. I think you can elevate the PR now.

Thanks Florian! I'll make the necessary amendments.

**Pull request merged**
